#!/bin/sh -e
# Copyright 2021 joakimnyman
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=src
else
    export PYTHONPATH="src:$PYTHONPATH"
fi

flake8 --ignore E501
coverage run --source=src -m unittest -v "$@"
coverage report -m
python3 -m unittest -v "$@"
