#!/bin/sh -e
# Copyright 2021 Joakim Nyman
# See LICENSE file for licensing details.

if [ -z "$VIRTUAL_ENV" -a -d venv/ ]; then
    . venv/bin/activate
fi

if [ -z "$PYTHONPATH" ]; then
    export PYTHONPATH=src
else
    export PYTHONPATH="src:$PYTHONPATH"
fi

python3 -m flake8 --ignore E501 -v "$@"
python3 -m unittest -v "$@"
